### ISSUE TITLE
Don't use default (internal) visibility modifier in application code. Always user open/public/private/fileprivate.

### ISSUE THREAD

**Issue by AntonPalich** [badoo/swift-style-guide#10]
It helps to move code between modules easily

**Comment by BohdanOrlov** [comment]
As we discussed, it contributes to code quality by making you think about visibility thus hiding unnecessary implementation details and probably improving compilation time as well.

**Comment by shuaib** [comment]
There was a brief discussion about this issue and probably we should revote on this:

Here are my points against the rule:

1- "internal" is a perfectly valid access level, and having a blanket ban on it is unnecessary.
2- If "@testable" works for testing purposes, we don't need to make objects/methods public just for testing.
3- If we need to move a class into a different module, we should keep the original access level for methods, except making those ones public that need to be.

Maybe we should keep this rule for the main project only. Because main project should not be imported into any other module, thus internal/public is pretty much same in that case. However, in this case, we would need to make sure to redefine the access levels in case the class is taken out of main project and copied to a new module.

**Comment by geegaset** [comment]
I suppose the original idea was to encourage developers to use the least possible privileged access level. https://en.wikipedia.org/wiki/Principle_of_least_privilege
This idea sounds absolutely reasonable to me. I agree with @shuaib, "internal" is absolutely valid access level. I don't see any reason to ban it.
In application module there is almost no difference between internal / public access level. Therefore I don't see any reason to force developers to mark all their main bundle entities with public keyword.
